main: cc.chaoticweg.mc.LeaveAMessage.LAMPlugin
database: true

name: LeaveAMessage
version: 0.1
author: ChaoticWeg

description: Leave a message for another player, whether they're online or not

commands:
    msg:
        description: Leave a message for another player.
        usage: |
            LAM Usage: /msg <recipient> <message...>